config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :admins, skip: :registrations
  get 'leads/csv_list'

  root 'home#index'

  resources :leads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates_presence_of :name, :ip
  validates :email, presence: true, email: true
  validate :ip_check

  def ip_check
    errors.add(:ip, 'Ip address is not valid.') unless IPAddress.valid? ip
  end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def user_not_authorized
    flash[:alert] = 'Você não está autorizado a realizar essa ação.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[show edit update destroy]
  before_action :authenticate_admin!, only: %i[index edit update destroy csv_list]

  # GET /leads
  # GET /leads.json
  def index
    @leads = []
    @leads_more_ip_filter = []
    Lead.all.order(:name).distinct.group_by(&:ip).each do |ip_leads|
      if ip_leads[1].size > 2
        @leads_more_ip_filter += ip_leads[1]
      else
        @leads += ip_leads[1]
      end
    end
  end

  def csv_list
    @options = :email, { name: { display_name: 'nome' } }, :ip, { created_at: { display_name: 'data_hora' } }
    @database = 'email,nome,ip,data_hora'
    Lead.all.each do |lead|
      @database << "\n"
      @database << "#{lead.email},#{lead.name},#{lead.ip},#{lead.created_at.strftime('%Y-%m-%d %H:%M:%S')}"
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show; end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit; end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)
    @lead.ip = request.remote_ip
    Lead.exists?(email: @lead.email) ? return : @lead.save
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lead
    @lead = Lead.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lead_params
    params.require(:lead).permit(:name, :email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: %i[index new edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :picture, :text, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<section class="conteudo">
  <div class="container">
    <div class="row">

      <div class="col-md-6">
        <h2>Você está feliz com seu trabalho?</h2>
        <p class="text-one">Está desmotivado e tem dificuldades para encontrar oportunidades?</p>
        <p class="text-two">Já pensou em como seria espetacular trabalhar em um ambiente dinâmico e empreendedor?</p><p>
        <h3><span>Transformamos</span> e <span>conectamos</span> talentos como você às <span>melhores startups</span> do mercado!</h2>

      </div>

        <br>
        <div class="col-md-5">
          <div class="formulario">
            <div class="caixa">
              <%= form_with(model: Lead.new, remote: true) do |form| %>
                <div class="form-group" id="name-group">
                  <label class='control-label' for='lead_name'>Nome completo:</label>
                  <%= form.text_field :name, id: :lead_name, placeholder: "Nome", class: "form-control" %>
                  <div class="alert alert-danger error-lead-name" role="alert" style="display:none; margin-top: 10px;">
                    <%= fa_icon "exclamation-triangle" %>
                    <span class="sr-only">Error:</span>
                    Favor inserir o nome completo.
                  </div>
                </div>
                <div class="form-group" id='email-group'>
                  <label class="label-two control-label" for="lead_email">
                    E-mail:</label>
                  <%= form.text_field :email, id: :lead_email, placeholder: "Email", class: "form-control" %>
                  <div class="alert alert-danger error-lead-email" role="alert" style="display:none; margin-top: 10px;">
                    <%= fa_icon "exclamation-triangle" %>
                    <span class="sr-only">Error:</span>
                    Favor inserir um e-mail válido.
                  </div>
                </div>
            </div>
              <%= form.submit "QUERO TRABALHAR EM UMA STARTUP!" , :onclick => "return validate();" %>
              <% end %>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="posts">
  <% @posts.each do |post| %>
    <div class="row">
      <div class="col-md-6">
        <div class="post-img">
          <a href="/posts/<%= post.id %>"><img class="img-responsive" src="<%= post.picture %>"/></a>
        </div>
      </div>

      <div class="col-md-6">
        <div class="post-txt">
          <a href="/posts/<%= post.id %>">
            <h2><%= post.title %></h2>
          </a>
          <a href="/posts/<%= post.id %>">
            <p>
              <%= post.description %>
            </p>
          </a>
          <a class="btn btn-primary" href="javascript:fbShare('http://eunumastartup.com/posts/<%= post.id %>', 'Compartilhar', 'Compartilhar no Facebook', 'http://goo.gl/dS52U', 520, 350)">Compartilhe</a>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eu numa Startup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <% if Rails.env.production? %>
    <script type="text/javascript">
      (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
        },
        i[r].l = 1 * new Date();
        a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
      })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
      ga('create', 'UA-102649442-1', 'auto');
    </script>
    <% end %>
    <!-- Facebook Pixel Code -->
    <script>
      !function (f, b, e, v, n, t, s) {
        if (f.fbq)
          return;
        n = f.fbq = function () {
          n.callMethod
            ? n.callMethod.apply(n, arguments)
            : n.queue.push(arguments)
        };
        if (!f._fbq)
          f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = '2.0';
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s)
      }(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '1821347364846089'); // Insert your pixel ID here.
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1821347364846089&ev=PageView&noscript=1"/></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->

  </head>

  <body>
    <section class="header">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <a href="/"><%= image_tag("new-logo.png", style: 'margin-top: 15px;') %></a>
          </div>
          <%#<div class="col-md-6">
            <button class="button">
              <a href="#quero">QUERO TRABALHAR EM UM STARTUP!</a>
            </button>
          </div>%>
        </div>
      </div>
    </section>
    <section id="post" class="conteudo">
      <div class="container">
        <%= yield %>
      </div>
    </section>

    <section id="quero" class="conteudo">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="formulario">
              <h2>
                <span>Transforme sua carreira</span>
                AGORA!</span>
            </h2>
            <div class="caixa">
              <%= form_with(model: Lead.new, remote: true) do |form_footer| %>
              <div class="form-group" id="name-group-footer">
                <label class='control-label' for='lead_name_footer'>Nome completo:</label>
                <%= form_footer.text_field :name, id: :lead_name_footer, placeholder: "Nome", class: "form-control" %>
                <div class="alert alert-danger error-lead-name-footer" role="alert" style="display:none; margin-top: 10px;">
                  <%= fa_icon "exclamation-triangle" %>
                  <span class="sr-only">Error:</span>
                  Favor inserir o nome completo.
                </div>
              </div>
              <div class="form-group" id='email-group-footer'>
                <label class="label-two control-label" for="lead_email_footer">
                  E-mail:</label>
                <%= form_footer.text_field :email, id: :lead_email_footer, placeholder: "Email", class: "form-control" %>
                <div class="alert alert-danger error-lead-email-footer" role="alert" style="display:none; margin-top: 10px;">
                  <%= fa_icon "exclamation-triangle" %>
                  <span class="sr-only">Error:</span>
                  Favor inserir um e-mail válido.
                </div>
              </div>
            </div>
            <%= form_footer.submit "QUERO TRABALHAR EM UMA STARTUP!", class: "button" , :onclick => "return validateFooter();" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3>Compartilhe e ajude um amigo com sua
            <font>TRANSFORMAÇÃO</font>
          </h3>
          <div class="social">
            <a href="javascript:fbShare('http://eunumastartup.com/', 'Compartilhar', 'Compartilhar no Facebook', 'http://goo.gl/dS52U', 520, 350)">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
</html>

app/views/leads/_form.html.erb
<%= form_with(model: lead, local: true) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :lead_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :lead_email %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip, id: :lead_ip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leads/create.js.erb
var errorAmount = '<%= @lead.errors.size %>';
var errorMsg = '<%= j @lead.errors.full_messages.join(';') %>';
var errors = errorMsg.split(';');
if (errorAmount == 0) {
  toastr.success('Cadastro efetuado com sucesso!');
  $('#lead_name').val('');
  $('#lead_email').val('');
} else {
  for (var i = 0; i < Object.keys(errors).length; i++){
    toastr.error(errors[i]);
  }
}

app/views/leads/csv_list.html.erb
<%= @database.gsub(/\n/, '<br/>').html_safe %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<div  style="background-color:white">
  <div class="pull-right" style="padding: 10px;">
    <%= link_to "Sair", destroy_admin_session_path,  method: :delete, class: "btn btn-danger" %>
  </div>
  <h1>Contagem unica de Leads: <%= @leads.size %></h1>
  <h1>Contagem total de Leads: <%= @leads.size + @leads_more_ip_filter.size %></h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Ip</th>
        <th>Criado em</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @leads.each do |lead| %>
        <tr>
          <td><%= lead.name %></td>
          <td><%= lead.email %></td>
          <td><%= lead.ip %></td>
          <td><%= lead.created_at %></td>
          <td><%= link_to 'Editar', edit_lead_path(lead) %></td>
          <td><%= link_to 'Remover', lead, method: :delete, data: { confirm: 'TEM CERTEZA!?NÃO TEM VOLTA!' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Ip</th>
        <th>Criado em</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @leads_more_ip_filter.each do |lead| %>
        <tr>
          <td><%= lead.name %></td>
          <td><%= lead.email %></td>
          <td><%= lead.ip %></td>
          <td><%= lead.created_at %></td>
          <td><%= link_to 'Editar', edit_lead_path(lead) %></td>
          <td><%= link_to 'Remover', lead, method: :delete, data: { confirm: 'TEM CERTEZA!?NÃO TEM VOLTA!' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @lead.ip %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :post_picture %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :post_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Picture</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.picture %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= @post.text.html_safe %>